# Generated by Django 6.0.1 on 2026-02-01 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionID', models.IntegerField()),
                ('buyer', models.CharField(max_length=50)),
                ('seller', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(default='in progress', max_length=20)),
                ('time', models.CharField(max_length=50)),
                ('deliverables', models.CharField(default='null', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serviceID', models.AutoField(primary_key=True, serialize=False)),
                ('Profile_image', models.ImageField(blank=True, null=True, upload_to='services_profiles/')),
                ('Name', models.CharField(max_length=100)),
                ('Service_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone_number', models.IntegerField()),
                ('Qualification', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
                ('Youtube_link', models.CharField(max_length=200)),
                ('Buyer_ID', models.JSONField(blank=True, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('No_Of_Buyers', models.IntegerField(blank=True, default=0)),
                ('sellerID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=500)),
                ('BuyerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('serviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
            ],
        ),
    ]
