# Generated by Django 6.0.1 on 2026-01-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Phone_number', models.IntegerField()),
                ('Qualification', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
                ('Youtube_link', models.CharField(max_length=200)),
                ('Price', models.IntegerField()),
                ('Sell_state', models.BooleanField(default=False)),
                ('Buyer_ID', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
