# Generated by Django 6.0.1 on 2026-01-27 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_service_delete_book'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionID', models.IntegerField()),
                ('buyer', models.CharField(max_length=50)),
                ('seller', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(default='in progress', max_length=20)),
                ('time', models.CharField(max_length=50)),
                ('deliverables', models.CharField(default='null', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='userID',
        ),
        migrations.AddField(
            model_name='service',
            name='No_Of_Buyers',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='sellerID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='Buyer_ID',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=500)),
                ('BuyerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('serviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
            ],
        ),
    ]
