# Generated by Django 6.0.1 on 2026-01-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_service_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionID', models.IntegerField()),
                ('buyer', models.CharField(max_length=50)),
                ('seller', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(default='in progress', max_length=20)),
                ('time', models.CharField(max_length=50)),
                ('deliverables', models.CharField(default='null', max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='service',
            old_name='Buyer_ID',
            new_name='No_Of_Buyers',
        ),
    ]
